#spring配置
spring:
  application:
    #应用名称(服务提供者)
    name: system-web-service

#服务器配置
server:
  #端口
  port: 8000

#服务中心发现注册配置
eureka:
  client:
    #服务注册中心地址
    service-url:
      defaultZone:  http://127.0.0.1:9000/eureka

#feign远程调用配置
feign:
  hystrix:
    #开启熔断
    enabled: true
